# frozen_string_literal: true
source 'https://rubygems.org'
gem 'themoviedb'
gem 'rack'
gem 'rack-test'
gem 'sinatra'
gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'byebug'
gem 'nokogiri'
# gem "rails"
