# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a959fdac7de8ea41fd48be4e94cf4e560fe87b8cd3fcef9c59cfec9274867745ea8e92d8e7f3129c37f23343a8358e73c210665b6feb964c9e02e6b60ec7ec2c

test:
  secret_key_base: 5162a90edf62d94e4dbe641fdb69e6f976231b9b42775df40f2fbb6823fa1df35ff9becaa24d19a238535bb1942bb11e836705302a151b22be95e217fa106bdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
