# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db6570ed104e9ab643aa9d89c5cd069d6f1334d9570f4ae1a2919c2091d97852cda1a3618e7bf795657343a86881a036f34dd85f36ae28ecce2b6982aa51264

test:
  secret_key_base: 51c9b2a9a49c21ac91cd2f1d7d22b57ac2ed8be7637947bee5b0265b05ae6bb2483e30cc9331f7e3a1e7a30ab0db294d266139e9874c31af8addaace630bd288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
